# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9485355d7dffc624ceb006aed6c71e36d47468c49cdef57b50560be415c5116330ab913ecec419e9e9f2c22a25da8e468d084bf61cb20ff19f2c37da1b60c086

test:
  secret_key_base: ee4722d40bd548007bd69d9cfdfcdc748d2b0da4198e8620e2acf5e334b69f55c5d9070822089c3d1f7c54ab900d9b6d4af213f32e008dd25fa98fc5400f8831

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
